
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Nov 17 18:34:53 PST 2021
//----------------------------------------------------

package Example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 2;
  public static final int INTEGER = 11;
  public static final int INT_CONST = 13;
  public static final int COLON = 4;
  public static final int SEMI = 8;
  public static final int STR_CONST = 12;
  public static final int EOF = 0;
  public static final int BOOL_CONST = 10;
  public static final int RBRACKET = 6;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int LBRACKET = 5;
  public static final int RBRACE = 3;
  public static final int FLOAT = 9;
}

